# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/backendnode: container
    io.kubernetes.cri-o.ContainerType/db: container
    io.kubernetes.cri-o.SandboxID/backendnode: 9358bcc09179a0dd1dbb822ba4fd3a82055269e5a63587146146a21f00708b8
    io.kubernetes.cri-o.SandboxID/db: 9358bcc09179a0dd1dbb822ba4fd3a82055269e5a63587146146a21f00708b8
    io.kubernetes.cri-o.TTY/backendnode: "false"
    io.kubernetes.cri-o.TTY/db: "false"
    io.podman.annotations.autoremove/backendnode: "FALSE"
    io.podman.annotations.autoremove/db: "FALSE"
    io.podman.annotations.init/backendnode: "FALSE"
    io.podman.annotations.init/db: "FALSE"
    io.podman.annotations.privileged/backendnode: "FALSE"
    io.podman.annotations.privileged/db: "FALSE"
    io.podman.annotations.publish-all/backendnode: "FALSE"
    io.podman.annotations.publish-all/db: "FALSE"
    org.opencontainers.image.base.digest/backendnode: sha256:bf58bc6bfd2b90441ebc12ba8fe217886899d32404de99350c889140
    org.opencontainers.image.base.name/backendnode: docker.io/library/node:18
  creationTimestamp: "2023-01-17T16:49:20Z"
  labels:
    app: mypod
  name: my_pod
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - mysqld
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    - name: MYSQL_DATABASE
      value: Pcomida_db
    image: docker.io/library/mysql:latest
    name: db
    ports:
    - containerPort: 3000
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: 2a40b6b95c714ee2b50761f102753f9550f83bf3dd11f2a14f1eaae18ef09ad9-pvc
  - args:
    - npm
    - start
    env:
    - name: NODE_DOCKER_PORT
      value: "3000"
    image: localhost/backend-container:latest
    name: backendnode
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  enableServiceLinks: false
  hostname: my_pod
  restartPolicy: Never
  volumes:
  - name: 2a40b6b95c714ee2b50761f102753f9550f83bf3dd11f2a14f1eaae18ef09ad9-pvc
    persistentVolumeClaim:
      claimName: 2a40b6b95c714ee2b50761f102753f9550f83bf3dd11f2a14f1eaae18ef09ad9
status: {}

